linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - exhaustive

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/Dreamacro/clash)
      - default
  静态检查：
    去：'1.21'
  详尽的：
    默认表示详尽：true
